# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7d791c12a735c45ddae590a69e0c40e83bfe8b96608fc1efb6a38f8f0d60481b90536b272a8467d1b5eb82849bf7c470b4f89c7554c9acfbcd3f35dcf945e6f

test:
  secret_key_base: b85092913178a946c79ab0cb93933e09b63638d6b7e6df87fa9809bb57f58814c4ab713aa1a4e9b5dcb60726416b14982421d1fb3da1f0c24fc18aa3b4b043ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
